spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 17447484718-e76uttlafk3jgs6p6f7a1fcn20qdeme1.apps.googleusercontent.com
            client-secret: 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